version: '3.4'

services:
  bookstorage.api:
    image: ${DOCKER_REGISTRY-}bookstorageapi
    depends_on:
        - "postgres_db"
    build:
      context: .
      dockerfile: BookStorage.API/Dockerfile

  postgres_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
        POSTGRES_DB: "${DB_NAME}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
