version: '3.4'

networks:
  bookstorage-dev-net:
    driver: bridge

services:
  bookstorage.api:
    image: ${DOCKER_REGISTRY-}bookstorageapi
    ports:
        - "85:8080"
    depends_on:
        - "bookstorage.postgres_db"
    build:
      context: .
      dockerfile: BookStorage.API/Dockerfile
    networks:
      - bookstorage-dev-net

  bookstorage.postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5436:5432"
    volumes: 
      - db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "${DB_NAME}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
      - bookstorage-dev-net
  
  bookstorage.react-spa:
    depends_on:
        - "bookstorage.api"
    build:
      context: .
      dockerfile: book-storage-spa/Dockerfile
    ports:
        - "2092:80"
    restart: always
    networks:
      - bookstorage-dev-net

volumes: 
  db_volume:
